/*******************************************************************************
*
*  Copyright 2011 Drakenclimber, LLC.
*
*  Licensed under the Apache License, Version 2.0 (the "License");
*  you may not use this file except in compliance with the License.
*  You may obtain a copy of the License at
*
*  http://www.apache.org/licenses/LICENSE-2.0
*
*  Unless required by applicable law or agreed to in writing, software
*  distributed under the License is distributed on an "AS IS" BASIS,
*  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*  See the License for the specific language governing permissions and
*  limitations under the License.
*
********************************************************************************
* Revision information.  DO NOT MODIFY.  This is auto-generated by the SCM.
*
* $Date: 2011-11-14 21:38:18 -0600 (Mon, 14 Nov 2011) $
* $Revision: 14 $
*
*******************************************************************************/
/**
* Doxygen comment block
* @file
*
* @brief   Android interface for the accelerometer service 
*
* @note    This interface provides a means to send information from the activity
*          to the service
*/

package com.drakenclimber.accelservice;

/*******************************************************************************
 * Imports
 ******************************************************************************/
import com.drakenclimber.accelservice.IAccelerometerListener;

/*******************************************************************************
 * Interfaces
 ******************************************************************************/
public interface IAccelerometerMonitor {
    /** register a callback to listen to the accelerometer service */
    void registerListener(IAccelerometerListener callback);

    /** unregister an accelerometer service listener */
    void unregisterListener(IAccelerometerListener callback);
}
